/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Graph_OpenOptions */

#ifndef _Included_Graph_OpenOptions
#define _Included_Graph_OpenOptions
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
