/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Graph */

#ifndef _Included_Graph
#define _Included_Graph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Graph
 * Method:    get_id
 * Signature: (LNode;)I
 */
JNIEXPORT jint JNICALL Java_Graph_get_1id__LNode_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Graph
 * Method:    get_id
 * Signature: (LEdge;)I
 */
JNIEXPORT jint JNICALL Java_Graph_get_1id__LEdge_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Graph
 * Method:    get_nodes
 * Signature: ()LNodeIterator;
 */
JNIEXPORT jobject JNICALL Java_Graph_get_1nodes
  (JNIEnv *, jobject);

/*
 * Class:     Graph
 * Method:    remove
 * Signature: (LNode;)V
 */
JNIEXPORT void JNICALL Java_Graph_remove__LNode_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Graph
 * Method:    remove
 * Signature: (LEdge;)V
 */
JNIEXPORT void JNICALL Java_Graph_remove__LEdge_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Graph
 * Method:    dumpGraph
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Graph_dumpGraph
  (JNIEnv *, jobject);

/*
 * Class:     Graph
 * Method:    loadGraphNative
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Graph_loadGraphNative
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Graph
 * Method:    addNodeNative
 * Signature: (LNode;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Graph_addNodeNative
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     Graph
 * Method:    addEdgeNative
 * Signature: (LEdge;LNode;LNode;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Graph_addEdgeNative
  (JNIEnv *, jobject, jobject, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
