/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Graph_IndexOptions */

#ifndef _Included_Graph_IndexOptions
#define _Included_Graph_IndexOptions
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
