/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NodeIterator */

#ifndef _Included_NodeIterator
#define _Included_NodeIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NodeIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_NodeIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     NodeIterator
 * Method:    nextNative
 * Signature: ()LNode;
 */
JNIEXPORT jobject JNICALL Java_NodeIterator_nextNative
  (JNIEnv *, jobject);

/*
 * Class:     NodeIterator
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NodeIterator_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
