/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Node */

#ifndef _Included_Node
#define _Included_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Node
 * Method:    get_tag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Node_get_1tag
  (JNIEnv *, jobject);

/*
 * Class:     Node
 * Method:    check_property
 * Signature: (Ljava/lang/String;LProperty;)Z
 */
JNIEXPORT jboolean JNICALL Java_Node_check_1property
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     Node
 * Method:    get_property
 * Signature: (Ljava/lang/String;)LProperty;
 */
JNIEXPORT jobject JNICALL Java_Node_get_1property
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Node
 * Method:    set_property
 * Signature: (Ljava/lang/String;LProperty;)V
 */
JNIEXPORT void JNICALL Java_Node_set_1property
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     Node
 * Method:    remove_property
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Node_remove_1property
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Node
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Node_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
