/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Property */

#ifndef _Included_Property
#define _Included_Property
#ifdef __cplusplus
extern "C" {
#endif
#undef Property_t_novalue
#define Property_t_novalue 1L
#undef Property_t_boolean
#define Property_t_boolean 2L
#undef Property_t_integer
#define Property_t_integer 3L
#undef Property_t_string
#define Property_t_string 4L
#undef Property_t_float
#define Property_t_float 5L
#undef Property_t_time
#define Property_t_time 6L
#undef Property_t_blob
#define Property_t_blob 7L
/*
 * Class:     Property
 * Method:    type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Property_type
  (JNIEnv *, jobject);

/*
 * Class:     Property
 * Method:    bool_value
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Property_bool_1value
  (JNIEnv *, jobject);

/*
 * Class:     Property
 * Method:    int_value
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Property_int_1value
  (JNIEnv *, jobject);

/*
 * Class:     Property
 * Method:    string_value
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Property_string_1value
  (JNIEnv *, jobject);

/*
 * Class:     Property
 * Method:    float_value
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Property_float_1value
  (JNIEnv *, jobject);

/*
 * Class:     Property
 * Method:    newPropertyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Property_newPropertyNative__
  (JNIEnv *, jobject);

/*
 * Class:     Property
 * Method:    newPropertyNative
 * Signature: (LProperty;)V
 */
JNIEXPORT void JNICALL Java_Property_newPropertyNative__LProperty_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Property
 * Method:    newPropertyNative
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Property_newPropertyNative__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Property
 * Method:    newPropertyNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Property_newPropertyNative__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     Property
 * Method:    newPropertyNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Property_newPropertyNative__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Property
 * Method:    newPropertyNative
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Property_newPropertyNative__D
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
