/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PropertyPredicate */

#ifndef _Included_PropertyPredicate
#define _Included_PropertyPredicate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PropertyPredicate
 * Method:    genericPropertyPredicateNative
 * Signature: (ILjava/lang/String;LPropertyPredicate/op_t;LProperty;LProperty;)V
 */
JNIEXPORT void JNICALL Java_PropertyPredicate_genericPropertyPredicateNative
  (JNIEnv *, jobject, jint, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
