/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Transaction */

#ifndef _Included_Transaction
#define _Included_Transaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Transaction
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Transaction_commit
  (JNIEnv *, jobject);

/*
 * Class:     Transaction
 * Method:    startTransactionNative
 * Signature: (LGraph;I)V
 */
JNIEXPORT void JNICALL Java_Transaction_startTransactionNative
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
